In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [29]:
agg = pd.read_csv('../data/senate_general_zip_20_22.csv')
agg['ZIP_CODE'] = agg['ZIP_CODE'].astype(str).str.zfill(5)

In [30]:
census = pd.read_csv('../data/census_cleaned.csv')
census["zip_code"] = census["zip_code"].astype(str).str.zfill(5)

census

      zip_code  population  median_income
0        00601       17242          19454
1        00602       37548          21420
2        00603       49804          20933
3        00606        5009          20992
4        00610       25731          24496
...        ...         ...            ...
30409    99921        1626          64250
30410    99922         380          46875
30411    99925         784          61250
30412    99926        1562          72279
30413    99929        2079          64375

[30414 rows x 3 columns]

# senate election schedules

In [31]:
# from milestone 2, manually collected
election_states20 = [
    "AL", "AK", "AZ", "AR", "CO", "DE", "GA", "ID", "IL", "IA",
    "KS", "KY", "LA", "ME", "MA", "MI", "MN", "MS", "MT", "NE",
    "NH", "NJ", "NM", "NC", "OK", "OR", "RI", "SC", "SD", "TN",
    "TX", "VA", "WV", "WY"
]

election_states22 = [
    "AL","AK","AZ","AR","CA","CO","CT","FL","GA","HI","ID","IL","IN","IA",
    "KS","KY","LA","MD","MO","NV","NH","NY","NC","ND","OH","OK","OR","PA",
    "SC","SD","UT","VT","WA","WI"
]

In [32]:
senate_class_states = {
    1: [
        "AZ","CA","CT","DE","FL","HI","IN","ME","MD","MA","MI","MN","MS",
        "MO","MT","NE","NV","NJ","NM","NY","ND","OH","PA","RI","TN","TX",
        "UT","VT","VA","WA","WV","WI","WY"
    ],

    2: [
        "AL","AK","AR","CO","DE","GA","ID","IL","IA","KS","KY","LA","ME",
        "MA","MI","MN","MS","MT","NE","NH","NJ","NM","NC","OK","OR","RI",
        "SC","SD","TN","TX","VA","WV","WY"
    ],

    3: [
        "AL","AK","AZ","AR","CA","CO","CT","FL","GA","HI","ID","IL","IN",
        "IA","KS","KY","LA","MD","MO","NV","NH","NY","NC","ND","OH","OK",
        "OR","PA","SC","SD","UT","VT","WA","WI"
    ],
}

In [33]:
# from 2016-2025, choosing to omit 2021 special runoff in GA
special_elections = [("CA", 2024), ("NE", 2024), ("OK", 2022), ("CA", 2022), ("GA", 2020), ("AZ", 2020),
                     ("MS", 2018), ("MN", 2018), ("AL", 2017)]

In [34]:
# election states in 2020 and 2022 based on senate class and special elections
elections_2020 = sorted(set(senate_class_states[2]) | {"GA", "AZ"})
elections_2022 = sorted(set(senate_class_states[3]) | {"OK", "CA"})

In [35]:
# check to make sure they agree with manual collection
missing_2020 = sorted(set(election_states20) - set(elections_2020))
print("Missing from 2020:", missing_2020)

missing_2022 = sorted(set(election_states22) - set(elections_2022))
print("Missing from 2022:", missing_2022)

extra_2020 = sorted(set(elections_2020) - set(election_states20))
print("Extra in 2020:", extra_2020)

extra_2022 = sorted(set(elections_2022) - set(election_states22))
print("Extra in 2022:", extra_2022)

Missing from 2020: []
Missing from 2022: []
Extra in 2020: []
Extra in 2022: []

In [36]:
agg

,ZIP_CODE,sum_20,count_20,sum_22,count_22,lat,lng,state_id
0,00602,175.0,11.0,0.0,0.0,18.36075,-67.17541,PR
1,00603,50.0,1.0,0.0,0.0,18.45744,-67.12225,PR
2,00612,500.0,1.0,0.0,0.0,18.41283,-66.70510,PR
3,00616,1250.0,2.0,0.0,0.0,18.41878,-66.66790,PR
4,00624,600.0,6.0,0.0,0.0,18.05905,-66.71932,PR
...,...,...,...,...,...,...,...,...
18619,99918,0.0,0.0,100.0,1.0,55.94605,-132.74233,AK
18620,99921,100.0,1.0,100.0,1.0,55.51989,-132.81656,AK
18621,99925,1500.0,2.0,0.0,0.0,55.55398,-132.96276,AK
18622,99926,50.0,1.0,0.0,0.0,55.12617,-131.48928,AK
18623,99929,250.0,1.0,100.0,1.0,56.36089,-132.00635,AK

In [37]:
# indicator(election in 2022) - indicator(election in 2020)
agg["election_2020"] = agg["state_id"].apply(lambda x: 1 if x in elections_2020 else 0)
agg["election_2022"] = agg["state_id"].apply(lambda x: 1 if x in elections_2022 else 0)
agg["election_diff"] = agg["election_2022"] - agg["election_2020"]

In [38]:
agg

,ZIP_CODE,sum_20,count_20,sum_22,count_22,lat,lng,state_id,election_2020,election_2022,election_diff
0,00602,175.0,11.0,0.0,0.0,18.36075,-67.17541,PR,0,0,0
1,00603,50.0,1.0,0.0,0.0,18.45744,-67.12225,PR,0,0,0
2,00612,500.0,1.0,0.0,0.0,18.41283,-66.70510,PR,0,0,0
3,00616,1250.0,2.0,0.0,0.0,18.41878,-66.66790,PR,0,0,0
4,00624,600.0,6.0,0.0,0.0,18.05905,-66.71932,PR,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
18619,99918,0.0,0.0,100.0,1.0,55.94605,-132.74233,AK,1,1,0
18620,99921,100.0,1.0,100.0,1.0,55.51989,-132.81656,AK,1,1,0
18621,99925,1500.0,2.0,0.0,0.0,55.55398,-132.96276,AK,1,1,0
18622,99926,50.0,1.0,0.0,0.0,55.12617,-131.48928,AK,1,1,0
18623,99929,250.0,1.0,100.0,1.0,56.36089,-132.00635,AK,1,1,0

In [42]:
# select columns zip_code and elections
zip_to_election_diff = agg[["ZIP_CODE", "election_2020", "election_2022", "election_diff"]]
# save to csv
zip_to_election_diff.to_csv('../data/zip_to_election_diff.csv', index=False)

# bachelor's degree

In [44]:
census_edu = pd.read_csv("../data/raw/ACSST5Y2024.S1501-Data.csv", dtype=str)
census_edu = census_edu.iloc[1:].copy()
census_edu.head()

,GEO_ID,NAME,S1501_C01_001E,S1501_C01_001M,S1501_C01_002E,S1501_C01_002M,S1501_C01_003E,S1501_C01_003M,S1501_C01_004E,S1501_C01_004M,...,S1501_C06_060M,S1501_C06_061E,S1501_C06_061M,S1501_C06_062E,S1501_C06_062M,S1501_C06_063E,S1501_C06_063M,S1501_C06_064E,S1501_C06_064M,Unnamed: 770
1,860Z200US00601,ZCTA5 00601,1253,254,103,72,324,192,756,255,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),NaN
2,860Z200US00602,ZCTA5 00602,3048,37,145,91,781,222,1650,273,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),NaN
3,860Z200US00603,ZCTA5 00603,4285,330,363,152,1581,284,1974,351,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),NaN
4,860Z200US00606,ZCTA5 00606,356,99,25,37,168,90,163,80,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),NaN
5,860Z200US00610,ZCTA5 00610,2149,40,116,78,670,221,804,220,...,(X),(X),(X),(X),(X),(X),(X),(X),(X),NaN

In [ ]:
cols = [
    "S1501_C01_001E",  # population 18 to 24
    "S1501_C01_003E",  # 18 to 24, high school graduate
    "S1501_C01_004E",  # 18 to 24, some college or associate's degree
    "S1501_C01_005E",  # 18 to 24, bachelor's degree or higher
    "S1501_C01_006E",  # population 25 years and over
    "S1501_C01_014E",  # 25+, high school graduate or higher
    "S1501_C01_015E",  # 25+, bachelor's degree or higher
]

census_edu[cols] = census_edu[cols].apply(pd.to_numeric, errors="coerce")

# Denominator: population age 18+
census_edu["educ_attainment_pop_18plus"] = (
    census_edu["S1501_C01_001E"] +
    census_edu["S1501_C01_006E"]
)

# Numerator: bachelor's degree or higher, age 18+
census_edu["college_degree_or_higher_count_18plus"] = (
    census_edu["S1501_C01_005E"] +   # 18-24 bachelor's or higher
    census_edu["S1501_C01_015E"]     # 25+ bachelor's or higher
)

census_edu["prop_college_degree_or_higher_18plus"] = (
    census_edu["college_degree_or_higher_count_18plus"] /
    census_edu["educ_attainment_pop_18plus"]
)

# Numerator: high school degree or higher, age 18+
census_edu["high_school_or_higher_count_18plus"] = (
    census_edu["S1501_C01_003E"] +   # 18-24 high school graduate
    census_edu["S1501_C01_004E"] +   # 18-24 some college/associate's
    census_edu["S1501_C01_005E"] +   # 18-24 bachelor's or higher
    census_edu["S1501_C01_014E"]     # 25+ high school graduate or higher
)

census_edu["prop_high_school_or_higher_18plus"] = (
    census_edu["high_school_or_higher_count_18plus"] /
    census_edu["educ_attainment_pop_18plus"]
)

# Clean impossible divisions
for c in [
    "prop_college_degree_or_higher_18plus",
    "prop_high_school_or_higher_18plus",
]:
    census_edu[c] = census_edu[c].replace([np.inf, -np.inf], np.nan)

census_edu["zip"] = census_edu["GEO_ID"].str[-5:]

educ_zip = census_edu[
    [
        "zip",
        "educ_attainment_pop_18plus",
        "college_degree_or_higher_count_18plus",
        "prop_college_degree_or_higher_18plus",
        "high_school_or_higher_count_18plus",
        "prop_high_school_or_higher_18plus",
    ]
]

educ_zip.head()

,zip,educ_attainment_pop_18plus,college_degree_or_higher_count_18plus,prop_college_degree_or_higher_18plus,high_school_or_higher_count_18plus,prop_high_school_or_higher_18plus
1,00601,13764,2346,0.170445,10004,0.726824
2,00602,31673,7140,0.225429,23100,0.729328
3,00603,40674,10698,0.263018,32476,0.798446
4,00606,4338,526,0.121254,2637,0.607884
5,00610,21548,4969,0.230601,16585,0.769677

In [48]:
educ_zip.to_csv('../data/zip_to_education.csv', index=False)